# Configurations for Machine Learning Pipeline

technique:
  - name: "classicML"
    algorithms:
      names: []
    feature_engineering:
      steps: ["shufle_data"] #TODO: remove from here since is part of every step
      columns: ["authors", "source", "publish_date", "is_fake"]
    modeling:
    evaluate:
